/**
 * Context Capsule — Exporter
 *
 * Writes a ContextCapsule to disk as both a human-readable .capsule.md
 * and a machine-readable .capsule.json. The Markdown version is optimized
 * for pasting directly into a new chat session.
 */
import { writeFile, mkdir } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { homedir } from 'node:os'
import type { ContextCapsule } from '../types.js'
import { getShortModelName } from '../models.js'

function getCapsuleDir(): string {
  return join(homedir(), '.continuum', 'capsules')
}

function safeFileName(s: string): string {
  return s.replace(/[^a-zA-Z0-9_-]/g, '_').replace(/_+/g, '_').slice(0, 60)
}

function formatMarkdown(capsule: ContextCapsule): string {
  const timestamp = new Date(capsule.generatedAt).toLocaleString()
  const modelShort = getShortModelName(capsule.model)

  const sections: string[] = [
    `#  Context Capsule`,
    ``,
    `> Generated by **Continuum** at ${timestamp}`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| Project | \`${capsule.project}\` |`,
    `| Previous Model | ${modelShort} |`,
    `| Provider | ${capsule.provider} |`,
    `| Session ID | \`${capsule.sessionId}\` |`,
    `| Context Used | ${capsule.utilizationPercent}% (${capsule.tokensUsed.toLocaleString()} / ${capsule.contextWindowSize.toLocaleString()} tokens) |`,
    ``,
    `## Summary`,
    ``,
    capsule.summary,
    ``,
  ]

  if (capsule.keyDecisions.length > 0) {
    sections.push(`## Key Decisions`, ``)
    for (const d of capsule.keyDecisions) sections.push(`- ${d}`)
    sections.push(``)
  }

  sections.push(`## Current Task`, ``, capsule.currentTask, ``)

  if (capsule.openQuestions.length > 0) {
    sections.push(`## Open Questions`, ``)
    for (const q of capsule.openQuestions) sections.push(`- ${q}`)
    sections.push(``)
  }

  if (capsule.recentTools.length > 0) {
    sections.push(`## Recently Used Tools`, ``, capsule.recentTools.join(', '), ``)
  }

  sections.push(
    `---`,
    ``,
    `## Continuation Prompt`,
    ``,
    `> Paste the block below as your first message in the new session.`,
    ``,
    '```',
    capsule.continuationPrompt,
    '```',
    ``,
  )

  return sections.join('\n')
}

export type CapsuleExportResult = {
  mdPath: string
  jsonPath: string
}

export async function exportCapsule(
  capsule: ContextCapsule,
  outputDir?: string,
): Promise<CapsuleExportResult> {
  const dir = outputDir ? resolve(outputDir) : getCapsuleDir()
  await mkdir(dir, { recursive: true })

  const datePart = new Date().toISOString().slice(0, 10)
  const namePart = safeFileName(capsule.project)
  const baseName = `${namePart}_${datePart}`

  const mdPath = join(dir, `${baseName}.capsule.md`)
  const jsonPath = join(dir, `${baseName}.capsule.json`)

  await Promise.all([
    writeFile(mdPath, formatMarkdown(capsule), 'utf-8'),
    writeFile(jsonPath, JSON.stringify(capsule, null, 2), 'utf-8'),
  ])

  return { mdPath, jsonPath }
}

/** Write capsule to the current working directory (convenient for CLI) */
export async function exportCapsuleToCwd(capsule: ContextCapsule): Promise<CapsuleExportResult> {
  return exportCapsule(capsule, process.cwd())
}
